image: $helm_registry_image:$helm_registry_version

variables:
  FAILFASTCI_NAMESPACE: joejulian-robot1
  registry: quay.io
  registry_user: joejulian
  chart_name: nginx-ingress
  robot_account: nginx_ingress
  helm_registry_image: quay.io/samsung_cnct/helm-registry-agent
  helm_registry_version: v0.1.5

stages:
  - build
  - test
  - publish

before_script:
  - helm registry login -u ${registry_user}+${robot_account} -p ${REGISTRY_PASSWORD}

build_chart:
  stage: build
  script:
    - build/build.sh

helm_test:
  stage: test
  script:
    - build/test.sh

helm_publish:
  stage: publish
  script:
    - helm registry push ${registry}/${registry_user}/${chart_name} -c alpha
